import React, { useState } from "react";
import ScheduleGrid from "./ScheduleGrid.jsx";




const UBC_COURSES = [
  "CPSC100", "CPSC103", "CPSC107", "CPSC110", "CPSC121",
  "CPSC210", "CPSC213", "CPSC221", "CPSC259", "CPSC304",
  "CPSC310", "CPSC311", "CPSC312", "CPSC313", "CPSC314",
  "CPSC317", "CPSC319", "CPSC320", "CPSC322", "CPSC330",
  "CPSC340", "CPSC344",
  "MATH100", "MATH101", "MATH102", "MATH103",
  "MATH104", "MATH105", "MATH110", "MATH200",
  "MATH215", "MATH221",
  "STAT200", "STAT201", "STAT203", "STAT241",
  "BIOL111", "BIOL112", "BIOL121",
  "CHEM121", "CHEM123",
  "SCIE113",
];

// color palette for courses (same course -> same color)
const COURSE_COLORS = [
  "#bfdbfe", // blue
  "#fecaca", // red
  "#bbf7d0", // green
  "#fde68a", // yellow
  "#f5d0fe", // purple
  "#fed7aa", // orange
  "#a5f3fc", // teal
];

function getColorForCourse(courseName) {
  let hash = 0;
  for (let i = 0; i < courseName.length; i++) {
    hash = (hash * 31 + courseName.charCodeAt(i)) | 0;
  }
  const index = Math.abs(hash) % COURSE_COLORS.length;
  return COURSE_COLORS[index];
}

export default function CourseSearch() {
  const [query, setQuery] = useState("");
  const [selectedCourses, setSelectedCourses] = useState([]);
  const [hovered, setHovered] = useState(null);

  // schedules generated by the algo (each item is one schedule = array of sections)
  const [generatedSchedules, setGeneratedSchedules] = useState([]);

  const filteredCourses = UBC_COURSES.filter((course) =>
    course.toLowerCase().includes(query.toLowerCase())
  );

  const handleSelectCourse = (course) => {
    if (!selectedCourses.includes(course)) {
      setSelectedCourses([...selectedCourses, course]);
    }
    setQuery("");
  };

  const handleRemoveCourse = (courseToRemove) => {
    const newSelected = selectedCourses.filter((c) => c !== courseToRemove);
    setSelectedCourses(newSelected);

    // optional: if removed everything, clear schedules too
    if (newSelected.length === 0) {
      setGeneratedSchedules([]);
    }
  };

  // 🔥 Use your partner's optimizeSchedules wrapper here
  const handleGenerateSchedule = () => {
    if (selectedCourses.length === 0) {
      setGeneratedSchedules([]);
      return;
    }

    // For now, no extra filters; you can plug real options later
    const options = {
      // noClassDays: ["Fri"],
      // minStart: "09:00",
      // maxEnd: "18:00",
      // preferredTimes: { ... }
    };

    const results = optimizeSchedules(selectedCourses, options);
    setGeneratedSchedules(results); // array of schedules → ScheduleGrid
  };

  return (
    <div style={styles.page}>
      {/* LEFT COLUMN */}
      <div style={styles.leftColumn}>
        {/* WHITE CARD that wraps everything */}
        <div style={styles.card}>
          {/* SEARCH AREA (with overlay dropdown) */}
          <div style={styles.searchArea}>
            <div style={styles.searchWrapper}>
              <span style={styles.icon}>🔍</span>
              <input
                type="text"
                placeholder="Search UBC courses (e.g. CPSC110)"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                style={styles.input}
              />
            </div>

            {query !== "" && (
              <ul style={styles.resultsList}>
                {filteredCourses.length > 0 ? (
                  filteredCourses.map((course) => (
                    <li
                      key={course}
                      style={styles.resultItem}
                      onClick={() => handleSelectCourse(course)}
                    >
                      {course}
                    </li>
                  ))
                ) : (
                  <li style={styles.noResult}>No matching course found</li>
                )}
              </ul>
            )}
          </div>

          {/* SELECTED COURSES */}
          {selectedCourses.length > 0 && (
            <div style={styles.selectedWrapper}>
              <div style={styles.selectedTitle}>Selected courses</div>
              <div style={styles.selectedList}>
                {selectedCourses.map((course) => {
                  const color = getColorForCourse(course);
                  return (
                    <div
                      key={course}
                      style={{
                        ...styles.selectedChip,
                        backgroundColor: color,
                      }}
                    >
                      <span>{course}</span>
                      <button
                        type="button"
                        style={{
                          ...styles.deleteButton,
                          color: hovered === course ? "#b91c1c" : "#111827",
                          fontWeight: hovered === course ? 700 : 500,
                        }}
                        onMouseEnter={() => setHovered(course)}
                        onMouseLeave={() => setHovered(null)}
                        onClick={() => handleRemoveCourse(course)}
                      >
                        ×
                      </button>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* GENERATE BUTTON */}
          <div style={styles.generateButtonWrapper}>
            <button
              onClick={handleGenerateSchedule}
              style={{
                ...styles.generateButton,
                opacity: selectedCourses.length === 0 ? 0.5 : 1,
                cursor: selectedCourses.length === 0 ? "not-allowed" : "pointer",
              }}
              disabled={selectedCourses.length === 0}
            >
              Generate schedule
            </button>
          </div>
        </div>
      </div>

      {/* RIGHT COLUMN: SCHEDULE GRID */}
      <div style={styles.rightColumn}>
        <ScheduleGrid
          schedules={generatedSchedules}
          getCourseColor={getColorForCourse} // so blocks match chips
        />
      </div>
    </div>
  );
}

//
// ===================== STYLES (unchanged) =====================
//

const styles = {
  page: {
    fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
    padding: "24px",
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    gap: "32px",
    background: "#e4e7ff", // your purple background
    minHeight: "100vh",
  },

  leftColumn: {
    flex: "0 0 380px",
  },

  card: {
    backgroundColor: "#ffffff",
    borderRadius: "20px",
    padding: "18px 18px 24px",
    boxShadow: "0 12px 30px rgba(15,23,42,0.15)",
    border: "1px solid rgba(148,163,184,0.25)",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },

  searchArea: {
    position: "relative",
    width: "100%",
  },

  searchWrapper: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    padding: "14px 16px",
    backgroundColor: "#ffffff",
    border: "1.5px solid #d1d5db",
    borderRadius: "18px",
  },

  icon: {
    marginRight: "10px",
    opacity: 0.7,
  },

  input: {
    flex: 1,
    border: "none",
    outline: "none",
    fontSize: "15px",
    background: "transparent",
    color: "#111827",
  },

  resultsList: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    marginTop: "6px",
    listStyle: "none",
    padding: "6px 0",
    backgroundColor: "#ffffff",
    border: "1.5px solid #d1d5db",
    borderRadius: "16px",
    boxShadow: "0 10px 24px rgba(15,23,42,0.18)",
    maxHeight: "220px",
    overflowY: "auto",
    zIndex: 10,
  },

  resultItem: {
    padding: "10px 16px",
    cursor: "pointer",
    fontSize: "15px",
    borderBottom: "1px solid #f3f4f6",
  },

  noResult: {
    padding: "10px 16px",
    fontSize: "14px",
    color: "#6b7280",
  },

  selectedWrapper: {
    marginTop: "6px",
  },

  selectedTitle: {
    fontSize: "15px",
    fontWeight: 600,
    marginBottom: "10px",
  },

  selectedList: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
  },

  selectedChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: "999px",
    color: "#111827",
    fontSize: "14px",
    fontWeight: 500,
    boxShadow: "0 4px 10px rgba(15,23,42,0.20)",
  },

  deleteButton: {
    border: "none",
    background: "transparent",
    cursor: "pointer",
    fontSize: "16px",
    padding: 0,
    lineHeight: 1,
  },

  generateButtonWrapper: {
    marginTop: "16px",
    display: "flex",
    justifyContent: "center",
  },

  generateButton: {
    padding: "12px 24px",
    borderRadius: "999px",
    border: "none",
    background: "linear-gradient(135deg, #22C55E, #3B82F6)",
    color: "#ffffff",
    fontWeight: 600,
    fontSize: "15px",
    boxShadow: "0 8px 20px rgba(37, 99, 235, 0.35)",
  },

  rightColumn: {
    flex: 1,
    minHeight: "400px",
    backgroundColor: "#ffffff",
    borderRadius: "20px",
    padding: "16px",
    boxShadow: "0 12px 30px rgba(15,23,42,0.15)",
    border: "1px solid rgba(148,163,184,0.25)",
  },
};
